### ISSUE TITLE
Border-radius property not working in outlook

### ISSUE THREAD

**Issue by untitledds** [bootstrap-email/bootstrap-email#133]
### Discussed in https://github.com/bootstrap-email/bootstrap-email/discussions/132

<div type='discussions-op-text'>

<sup>Originally posted by **untitledds** October 15, 2021</sup>
border-radius property is not supported by outlook, as it uses MS-word template. we need to code for outlook too.
   
 ```
<!--[if mso]>
      <v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" xmlns:w="urn:schemas-microsoft-com:office:word" href="http://example.com" style="height:36px;v-text-anchor:middle;width:150px;" arcsize="5%" strokecolor="#EB7035" fillcolor="#EB7035">
        <w:anchorlock/>
        <center style="color:#ffffff;font-family:Helvetica, Arial,sans-serif;font-size:16px;">I am a button &rarr;</center>
      </v:roundrect>
    <![endif]-->
```</div>

**Comment by Zomono** [comment]
Are there any plans to implement this feature?
Anyway, thanks for this project! It already saved a lot of time for me.

**Comment by stuyam** [comment]
I have spent some time investigating this. What I have found out is that the trade off to support rounded corners in Outlook is not worth it. Since rounded corners don't change things like layout and are mostly aesthetic, it isn't a hug deal to just have buttons or other things have square corners.

If we were to support this way of using the `<v:roundrect>` element in Outlook, it means the element would need:
1. A percentage based border radius which is hard to do dynamically.
2. Custom styles for colors and borders etc.
3. And perhaps worst of all it needs explicit with and height units in pixel which means it would not be dynamic based on the widths and heights or text inside of buttons for example.

I wish it was more straightforward but I haven't had any good results with this method and I think having square corners in outlook it a better tradeoff still.
