### ISSUE TITLE
Issue when sending with Mailgun after upgrade to 1.3.0

### ISSUE THREAD

**Issue by majksner** [bootstrap-email/bootstrap-email#199]
### What version of Bootstrap Email are you using?

v1.3.0

### How are you compiling?

Rails

### Describe your issue

After upgrade to v1.3.0 sending mail via Mailgun looks like this. Reverting to v1.2.0 mails look normal.

<img width="1447" alt="Screenshot 2022-07-07 at 12 20 30" src="https://user-images.githubusercontent.com/512355/177751968-9407cc0a-ebcb-4ce1-8164-18da4562e6e3.png">

**Comment by ojgarcia** [comment]
I had the same issue and I was not using mailgun.

**Comment by basabin54** [comment]
Also having issues with v1.3.0 and I'm also using mailgun

Looks like styles aren't being injected anymore, both with sending through mailgun and using letter_opener on local.

And not sure if this is related or not, but calling bootstrap_mail now returns an instance of BootstrapEmail::Rails::MailBuilder instead of an instance of Mail::Message and this is causing other things to break, like adding custom headers to messages for mailgun e.g.

bootstrap_mail(from: from, to: to, cc: cc, subject: subject).tap do |message|
      message.mailgun_options = { <= Breaks b/c BootstrapEmail::Rails::MailBuilder doesn't respond to mailgun_options
        "tracking-opens" => true,
        "tracking-clicks" => "htmlonly"
      }
    end

**Comment by jules-w2** [comment]
I have the same issue and I use SES
